### ISSUE TITLE
When I execute install.bash, some packages' paths are modified by euslime

### ISSUE THREAD

**Issue by mqcmd196** [jsk-ros-pkg/euslime#3]
Hi!
I executed these commands.
```bash
source /opt/ros/melodic/setup.bash
source ~/semi_ws/devel/setup.bash
```
Then I executed this commands,
```bash
rospack find pr2eus
```
terminal shows
```
/home/user/semi_ws/src/jsk_pr2eus/pr2eus
```

However after these commands, I executed
```bash
source ~/euslime_ws/install/setup.bash
rospack find pr2eus
```
and terminal shows,
```
/opt/ros/melodic/share/pr2eus
```

I want to use pr2eus in `semi_ws/src/jsk_pr2eus` on euslime. How can I fix this trouble?

Thanks.

**Comment by Affonso-Gui** [comment]
When you build a workspace it remembers all the packages sourced at the build time (this is a ROS thing and is not specifically related to euslime).

To use euslime with the pr2eus from source do:
- `(cd ~/euslime_ws ; catkin clean)`
- `source ~/semi_ws/devel/setup.bash`
- `catkin build`
Then whenever you start a new session just do `source ~/euslime_ws/install/setup.bash`. It will remember the previously sourced semi_ws.

Usually to avoid this kind of confusion it is recommended to have only one workspace. However, I do like to keep the euslime in a separate one, specially because it needs to be configured as an install one (it is possible to build it with devel as well, with a few hacks).

**Comment by mqcmd196** [comment]
I understood what `catkin build` did and succeeded in using pr2eus from source.

Thanks!
